### ISSUE TITLE
CPU 异常占用

### ISSUE THREAD

**Issue by aclstack** [langhuihui/monibuca#134]
目前只接入了两路摄像头，走的是GB协议。目前也没有人在线观看。服务器配置4C 8G
![image](https://github.com/langhuihui/monibuca/assets/17819228/0ded756f-671b-4713-ac73-478d59a3d7be)
配置文件做了这些优化
```
global:
  pulseinterval: 50s
  loglang: en

monitor:
  enable: false
llhls:
  enable: false
hls:
  enable: false
snap:
  enable: false
room:
  enable: false
rtmp:
  enable: false
rtsp:
  enable: false
webrtc:
  enable: false
webtransport:
  enable: false
jessica:
  enable: false
logrotate:
  enable: false
hook:
  enable: false
```
