### ISSUE TITLE
rtsp streaming in mp4 format!

### ISSUE THREAD

**Issue by smkhairkar** [langhuihui/monibuca#142]
How can I record an RTSP stream in MP4 format in chunks and then how to playback the same.

**Comment by langhuihui** [comment]
write config.yaml 
```yaml
rtsp:
  pull:
    pullonstart:
       live/test:  rtsp://yourrtspurl
record:
  mp4:
    autorecord: true
    fragment: 10s
```
then server will automatic pull the rtsp，and automatic record to mp4，every 10s create a file
