### ISSUE TITLE
大华摄像头GB28181接入m7s@v4.0.6，使用VLC读取rtsp流发现画面卡住不动

### ISSUE THREAD

**Issue by xvjialing** [langhuihui/monibuca#67]
试了很多工具发现只能用vlc打开rtsp流，而且发现画面卡在那个时间点不变化，地址为`rtsp://192.168.31.48:554/34020000001320000001/34020000001310000001`

![屏幕截图 2022-09-05 0939101](https://user-images.githubusercontent.com/15673470/188345548-d3af6db8-105b-471f-b725-892908364b3a.jpg)

m7s的配置文件如下：

```yaml
gb28181:
  autoinvite:     true
  prefetchrecord: false
  udpcachesize:   0
  sipnetwork:     udp
  sipip:          192.168.31.48
  sipport:        5060
  serial:         "34020000002000000001"
  realm:          "3402000000"
  username:       "34020000002000000001"
  password:       "123456"
  
  acktimeout:        10
  registervalidity:  60
  registerinterval:  60
  heartbeatinterval: 60
  heartbeatretry:    3
  
  mediaip:          192.168.31.48
  mediaport:        58200
  mediaidletimeout: 30
  medianetwork:     udp
  
  removebaninterval: 600
  loglevel:         info
  audioenable:       true
rtsp:
    publish:
        pubaudio: true
        pubvideo: true
        kickexist: false
        publishtimeout: 10
        waitclosetimeout: 0
    subscribe:
        subaudio: true
        subvideo: true
        iframeonly: false
        waittimeout: 10
    pull:
        repull: 0
        pullonstart: false
        pullonsubscribe: false
        pulllist: {}
    push:
        repush: 0
        pushlist: {}
    listenaddr: :554
    udpaddr: :8000
    rtcpaddr: :8001
    readbuffersize: 2048
    pullprotocol: 'auto'
hls:
    publish:
        pubaudio: true
        pubvideo: true
        kickexist: false
        publishtimeout: 10
        waitclosetimeout: 0
    pull:
        repull: -1
        pullonstart: false
        pullonsubscribe: true
        pulllist: {}
    subscribe:
        subaudio: true
        subvideo: true
        iframeonly: false
        waittimeout: 10
    fragment: 10
    window: 2
    filter: ""
```

大华摄像头配置如图：

![屏幕截图 2022-09-05 093926](https://user-images.githubusercontent.com/15673470/188345617-6a1ca88c-21c7-4d0b-a08b-ed99627254c7.png)

获取m7s关于流信息的api : `http://192.168.31.48:8080/api/stream?streamPath=34020000001320000001/34020000001310000001`返回
```json
{
  "StartTime": "2022-09-05T09:38:38.244292559+08:00",
  "PublishTimeout": 10000000000,
  "DelayCloseTimeout": 0,
  "Path": "34020000001320000001/34020000001310000001",
  "Publisher": {
    "ID": "",
    "Type": "GB28181 Live",
    "StartTime": "2022-09-05T09:38:38.244522351+08:00",
    "Args": {
      
    },
    "Start": "",
    "End": "",
    "SSRC": 200006552
  },
  "State": 1,
  "Subscribers": [
    {
      "ID": "",
      "Type": "HLSWriter",
      "StartTime": "2022-09-05T09:38:38.244985544+08:00",
      "Args": {
        
      }
    },
    {
      "ID": "",
      "Type": "RTSP",
      "StartTime": "2022-09-05T09:40:15.243394201+08:00",
      "Args": {
        
      }
    }
  ],
  "Tracks": [
    {
      "Name": "pcma",
      "BPS": 640,
      "FPS": 2,
      "RawPart": [
        39,
        221,
        139,
        232,
        145,
        95,
        11,
        195,
        74,
        194
      ],
      "RawSize": 319,
      "BPSs": [
        {
          "Timestamp": "2022-09-05T09:40:10.566714025+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:11.568324744+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:12.570020571+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:13.571258997+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:14.572768355+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:15.573614706+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:16.575564755+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:17.577910894+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:18.580295259+08:00",
          "Value": 640
        },
        {
          "Timestamp": "2022-09-05T09:40:19.582033445+08:00",
          "Value": 640
        }
      ],
      "FPSs": [
        {
          "Timestamp": "2022-09-05T09:40:10.566714025+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:11.568324744+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:12.570020571+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:13.571258997+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:14.572768355+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:15.573614706+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:16.575564755+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:17.577910894+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:18.580295259+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:19.582033445+08:00",
          "Value": 2
        }
      ],
      "Size": 32,
      "MoveCount": 203,
      "LastValue": {
        "DeltaTime": 960,
        "AbsTime": 47819576,
        "Timestamp": "2022-09-05T09:40:19.081628506+08:00",
        "Sequence": 202,
        "BytesIn": 320,
        "IFrame": false,
        "PTS": 3802430206,
        "DTS": 8801820
      },
      "Poll": 10000000,
      "SampleRate": 8000,
      "CodecID": 7,
      "Channels": 1,
      "SampleSize": 16,
      "AVCCHead": "cg==",
      "Profile": 0
    },
    {
      "Name": "h264",
      "BPS": 12619,
      "FPS": 2,
      "RawPart": [
        97,
        226,
        128,
        2,
        153,
        8,
        255,
        115,
        109,
        12
      ],
      "RawSize": 6232,
      "BPSs": [
        {
          "Timestamp": "2022-09-05T09:40:10.566627311+08:00",
          "Value": 13291
        },
        {
          "Timestamp": "2022-09-05T09:40:11.56824887+08:00",
          "Value": 13085
        },
        {
          "Timestamp": "2022-09-05T09:40:12.569939147+08:00",
          "Value": 18624
        },
        {
          "Timestamp": "2022-09-05T09:40:13.571158627+08:00",
          "Value": 12784
        },
        {
          "Timestamp": "2022-09-05T09:40:14.572702192+08:00",
          "Value": 18474
        },
        {
          "Timestamp": "2022-09-05T09:40:15.573548335+08:00",
          "Value": 12747
        },
        {
          "Timestamp": "2022-09-05T09:40:16.575501852+08:00",
          "Value": 16133
        },
        {
          "Timestamp": "2022-09-05T09:40:17.577847372+08:00",
          "Value": 12623
        },
        {
          "Timestamp": "2022-09-05T09:40:18.580229059+08:00",
          "Value": 16235
        },
        {
          "Timestamp": "2022-09-05T09:40:19.581954821+08:00",
          "Value": 12619
        }
      ],
      "FPSs": [
        {
          "Timestamp": "2022-09-05T09:40:10.566627311+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:11.56824887+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:12.569939147+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:13.571158627+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:14.572702192+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:15.573548335+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:16.575501852+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:17.577847372+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:18.580229059+08:00",
          "Value": 2
        },
        {
          "Timestamp": "2022-09-05T09:40:19.581954821+08:00",
          "Value": 2
        }
      ],
      "Size": 256,
      "MoveCount": 203,
      "LastValue": {
        "DeltaTime": 40,
        "AbsTime": 8080,
        "Timestamp": "2022-09-05T09:40:19.581955727+08:00",
        "Sequence": 202,
        "BytesIn": 6236,
        "IFrame": false,
        "PTS": 8801820,
        "DTS": 727200
      },
      "Poll": 10000000,
      "SampleRate": 90000,
      "CodecID": 7,
      "SPSInfo": {
        "ProfileIdc": 100,
        "LevelIdc": 31,
        "MbWidth": 80,
        "MbHeight": 45,
        "CropLeft": 0,
        "CropRight": 0,
        "CropTop": 0,
        "CropBottom": 0,
        "Width": 1280,
        "Height": 720
      },
      "GOP": 0
    }
  ],
  "AppName": "34020000001320000001",
  "StreamName": "34020000001310000001"
}
```
